<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fr3d_ldap.ldap_driver.zend' shared service.

return $this->services['fr3d_ldap.ldap_driver.zend'] = new \FR3D\LdapBundle\Driver\ZendLdapDriver(new \Zend\Ldap\Ldap($this->parameters['fr3d_ldap.ldap_driver.parameters']), ${($_ = isset($this->services['monolog.logger.ldap_driver']) ? $this->services['monolog.logger.ldap_driver'] : $this->load('getMonolog_Logger_LdapDriverService.php')) && false ?: '_'});
