<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fr3d_ldap.user_hydrator.default' shared service.

return $this->services['fr3d_ldap.user_hydrator.default'] = new \FR3D\LdapBundle\Hydrator\LegacyHydrator(${($_ = isset($this->services['fos_user.user_manager']) ? $this->services['fos_user.user_manager'] : $this->load('getFosUser_UserManagerService.php')) && false ?: '_'}, $this->parameters['fr3d_ldap.ldap_manager.parameters']);
