<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fr3d_ldap.ldap_manager.default' shared service.

return $this->services['fr3d_ldap.ldap_manager.default'] = new \FR3D\LdapBundle\Ldap\LdapManager(${($_ = isset($this->services['fr3d_ldap.ldap_driver.zend']) ? $this->services['fr3d_ldap.ldap_driver.zend'] : $this->load('getFr3dLdap_LdapDriver_ZendService.php')) && false ?: '_'}, ${($_ = isset($this->services['fr3d_ldap.user_hydrator.default']) ? $this->services['fr3d_ldap.user_hydrator.default'] : $this->load('getFr3dLdap_UserHydrator_DefaultService.php')) && false ?: '_'}, $this->parameters['fr3d_ldap.ldap_manager.parameters']);
