<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fr3d_ldap.validator.unique' shared service.

return $this->services['fr3d_ldap.validator.unique'] = new \FR3D\LdapBundle\Validator\UniqueValidator(${($_ = isset($this->services['fr3d_ldap.ldap_manager.default']) ? $this->services['fr3d_ldap.ldap_manager.default'] : $this->load('getFr3dLdap_LdapManager_DefaultService.php')) && false ?: '_'});
