<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fr3d_ldap.security.user.provider' shared service.

return $this->services['fr3d_ldap.security.user.provider'] = new \FR3D\LdapBundle\Security\User\LdapUserProvider(${($_ = isset($this->services['fr3d_ldap.ldap_manager.default']) ? $this->services['fr3d_ldap.ldap_manager.default'] : $this->load('getFr3dLdap_LdapManager_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.security']) ? $this->services['monolog.logger.security'] : $this->load('getMonolog_Logger_SecurityService.php')) && false ?: '_'});
