<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\DefaultController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ixwkmhy']) ? $this->services['service_locator.ixwkmhy'] : $this->load('getServiceLocator_IxwkmhyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ixwkmhy']) ? $this->services['service_locator.ixwkmhy'] : $this->load('getServiceLocator_IxwkmhyService.php')) && false ?: '_'};
})));
