<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Symfony\Component\Ldap\Ldap' shared autowired service.

return $this->services['Symfony\Component\Ldap\Ldap'] = new \Symfony\Component\Ldap\Ldap(new \Symfony\Component\Ldap\Adapter\ExtLdap\Adapter(array('host' => 'localhost', 'port' => 389, 'options' => array('protocol_version' => 3, 'referrals' => false))));
