<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.my_ldap' shared service.

return $this->services['security.user.provider.concrete.my_ldap'] = new \Symfony\Component\Security\Core\User\LdapUserProvider(${($_ = isset($this->services['Symfony\Component\Ldap\Ldap']) ? $this->services['Symfony\Component\Ldap\Ldap'] : $this->load('getLdapService.php')) && false ?: '_'}, 'DC=maxcrc,DC=com', 'CN=Manager,DC=maxcrc,DC=com', 'secret', array(0 => 'ROLE_USER'), 'sAMAccountName', '({uid_key}={username})', NULL);
