<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.ldap_bind.main' shared service.

return $this->services['security.authentication.provider.ldap_bind.main'] = new \Symfony\Component\Security\Core\Authentication\Provider\LdapBindAuthenticationProvider(${($_ = isset($this->services['security.user.provider.concrete.my_ldap']) ? $this->services['security.user.provider.concrete.my_ldap'] : $this->load('getSecurity_User_Provider_Concrete_MyLdapService.php')) && false ?: '_'}, new \Symfony\Component\Security\Core\User\UserChecker(), 'main', ${($_ = isset($this->services['Symfony\Component\Ldap\Ldap']) ? $this->services['Symfony\Component\Ldap\Ldap'] : $this->load('getLdapService.php')) && false ?: '_'}, 'maxcrc\\People\\{username}', true);
