<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3zoze5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3zoze5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX3zoze5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX3zoze5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX3zoze5\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X3zoze5',
    'container.build_id' => '7f385604',
    'container.build_time' => 1538131116,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3zoze5');
